
export const ADD_FAV = "ADD_FAV"
export const REMOVE_FAV = "REMOVE_FAV"
export const ADD_CHAR = "ADD_CHAR"
export const REMOVE_CHAR = "REMOVE_CHAR"
export const FILTER = "FILTER"
export const RESET = "RESET"
export const FILTER_A_Z = "FILTER_A_Z"
export const PREV = "PREV"
export const NEXT = "NEXT"
export const CREATE_CHAR = "CREATE_CHAR"
export const RESET_CHARACTERS = "RESET_CHARACTERS"
export const RESET_PAGE = "RESET_PAGE"
export const SEARCH_CHAR = "SEARCH_CHAR"